TD:
  TD_API_KEY: <API_KEY>
  TD_RESOURCE_URL: "https://api.tdameritrade.com/v1/marketdata/chains"

WATCHLIST: "watchlist.csv"
OUTPUT_FILE: "wheel.csv"

EXPIRYDATE: "YYYY-MM-DD"

PARAMS_BUYCALL:
  DELTA: 0.3
  DELTADEV: 0.05
  OPEN_INTEREST: 100
  NUM_CONTRACTS: 1
  CONTRACT_TYPE: "PUT"  # PUT or CALL
  OPTION_TYPE: "S"

PARAMS_SELLCALL:
  OPEN_INTEREST: 100
  NUM_CONTRACTS: 1

SSL:
  RETRIES: 3
  BACKOFF_FACTOR: 0.5
